services:
  app:
    image: granlobo2004/myerasmusjourney:${TAG}
    platform: linux/amd64

    ports:
      - target: 8443
        published: 8443

    environment:
      DB_URL: jdbc:mysql://db:3306/myerasmusjourney
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_MODE: update
      PORT: 8443
      SSL_ENABLED: true
      KEY_STORE: example.jks
      KEY_PASSWORD: password
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myerasmusjourney
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  db_data: