services:
  app:
    image: granlobo2004/myerasmusjourney:${TAG}
    platform: linux/amd64
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MODE: ${DB_MODE}
      PORT: ${PORT}
      SSL_ENABLED: ${SSL_ENABLED}
      KEY_STORE: ${KEY_STORE}
      KEY_PASSWORD: ${KEY_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: myerasmusjourney
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  db_data: