name: Full Test Suite

on:
  workflow_dispatch:
  pull_request:
    branches:
        - main

jobs:
  backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
        
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
            node-version: 24
            cache: pnpm
            cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: frontend

      - name: Run backend tests
        run: mvn clean test

  frontend:

    needs: backend

    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:9.3
            env:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: myerasmusjourney
            ports:
                - 3306:3306
            options: >-
                --health-cmd="mysqladmin ping -h localhost"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=10

    defaults:
        run:
            working-directory: frontend

    steps:

        - name: Clone repository
          uses: actions/checkout@v6

        - name: Set up JDK 21
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: '21'
            cache: maven

        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 11

        - name: Set up Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: pnpm
            cache-dependency-path: frontend/pnpm-lock.yaml

        - name: Install dependencies
          run: pnpm install

        - name: Create API REST package
          run: |
            cd ../backend
            mvn clean package -DskipTests

        - name: Run API REST
          env:
            DB_URL: jdbc:mysql://localhost:3306/myerasmusjourney
            DB_USERNAME: root
            DB_PASSWORD: root
            DB_MODE: create-drop
            PORT: 8080
            SSL_ENABLED: false

          run: |
            cd ../backend
            java -jar target/*.jar &
        
        - name: Wait for API REST
          run: |
            until curl -f http://localhost:8080/api/v1/experiences/ > /dev/null; do
            echo "Waiting for API REST..."
            sleep 2
            done
        
        - name: Run web tests
          env:
            VITE_API_URL: "http://localhost:8080/api/v1"
          run: pnpm --filter web test

        - name: Run shared tests
          run: pnpm --filter shared test